name: Deployment Workflow

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Set up Git user
      run: |
        git config --global user.name "Blaz Baskovc"
        git config --global user.email "blaz.baskovc@gmail.com"
    - name: Fetch all branches
      run: git fetch
    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Create new branch
      run: git checkout -b release/${VERSION}
    - name: Push release branch
      run: git push origin release/${VERSION}
    - name: Merge to main
      run: |
        git checkout main
        git merge --no-ff --allow-unrelated-histories release/${VERSION}
        git push origin main
    - name: Merge to develop
      run: |
        git checkout develop
        git merge --no-ff --allow-unrelated-histories main
        git push origin develop

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Delete tag and release branch
      run: |
        git push --delete origin ${VERSION} || true
        git push --delete origin release/${VERSION} || true

